project:
  type: website
  preview:
    port: 4322
execute:
  freeze: auto
  message: false
  warning: false
website:
  title: "[CÓDIGO DEL CURSO]: [Título del Curso]"
  # site-url: https://[username].github.io/[repo-name]/
  description: "Materiales del curso para [CÓDIGO DEL CURSO]"
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - index.qmd
      - horario.qmd
      - planes.qmd
      - diapositivas.qmd
    right:
      - actividades.qmd
format:
  html:
    link-external-newwindow: true
    theme: cosmo
    css:
      - assets/css/styles.css
      - include/webex.css
    toc: true
    toc-depth: 3
    include-after-body: include/webex.js
lang: es
